_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.9
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": linux-x86_64
CNR:
    value: 15
SNR:
    value: 10
batch_size:
    value: 16
beta_end:
    value: 0.02
beta_start:
    value: 0.0001
dataset_size:
    value: 50000
learning_rate:
    value: 0.0001
noise_steps:
    value: 2000
num_epochs:
    value: 400
num_workers:
    value: 4
scheduler_type:
    value: linear
time_emb_dim:
    value: 256
